### ISSUE TITLE
Need to remove the comma for the final attribute

### ISSUE THREAD

**Issue by shmilky** [rdegges/svcc-auth#2]
In Util.js there is a use of the client-sessions middleware that you need to fix..
app.use(session({
    cookieName: 'session',
    secret: 'keyboard cat',
    duration: 30 \* 60 \* 1000,
    activeDuration: 5 \* 60 \* 1000,
  }));

**Comment by rdegges** [comment]
That is valid JS -- won't break anything. You can definitely submit a PR if you'd like -- I'd be happy to accept it =)

**Comment by shmilky** [comment]
My bad, sorry (there is no need)

I’m not use to this convention and mistakenly I thought that it might cause problems

JS is much more forgiving than what I use to:)

BTW, used your guide on YouTube and it was very helpful!!! (https://www.youtube.com/watch?v=yvviEA1pOXw https://www.youtube.com/watch?v=yvviEA1pOXw&list=UUJI9gByFSXE1ABDRcLQjWgQ &list=UUJI9gByFSXE1ABDRcLQjWgQ)

Thanks a lot:)

**Comment by shmilky** [comment]
BTW, used your guide on YouTube and it was very helpful!!! (https://www.youtube.com/watch?v=yvviEA1pOXw <https://www.youtube.com/watch?v=yvviEA1pOXw&list=UUJI9gByFSXE1ABDRcLQjWgQ> &list=UUJI9gByFSXE1ABDRcLQjWgQ) 

Thanks a lot:)

**Comment by rdegges** [comment]
No problem! Glad ya liked the video ^^
