### ISSUE TITLE
Client-sessions 

### ISSUE THREAD

**Issue by igorvieira** [rdegges/svcc-auth#6]
Hello  I started doing a project similar to yours and me came a doubt the use of client- sessions  in which it differs from express-session has problems using the express-session for each working with sessions ?
Sorry I am from Brazil and meu Ingles is terrible 
but I thank you for your attention and your time

**Comment by rdegges** [comment]
client-sessions is a lot more secure than express-sessions, which is why it is used here =)

**Comment by igorvieira** [comment]
Thanks Man!
=)
