### ISSUE TITLE
invalid csrf token error

### ISSUE THREAD

**Issue by pingkoc** [rdegges/svcc-auth#7]
Hi,
I see that you committed a couple of days ago to fix the csrf issue by passing in csrfToken: req.csrfToken() to render. I was trying to test the incorrect login errors and encountered the invalid csrf token error on every other invalid attempt.
I managed to fix it by also passing in req.csrfToken() to the res.render that belongs to the if (!user) part.
I believe you must have meant it but just missed putting it in there as well.
Cheers!
Thanks for the great tutorial.

**Comment by rdegges** [comment]
Sorry for getting back late (holidays are busy!), but just fixed this =)
